name: CI/CD Pipeline for Terraform, Ansible, and Docker

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch.
  pull_request:
    branches:
      - main  # Trigger the workflow on pull requests to the 'main' branch.

jobs:
  # Terraform Job
  terraform:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      

      - name: Install Terraform
        run: |
          curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -
          sudo apt-add-repository "deb https://apt.releases.hashicorp.com $(lsb_release -cs) main"
          sudo apt-get update
          sudo apt-get install terraform

      - name: Initialize Terraform
        run: terraform init

      - name: Apply Terraform
        run: terraform apply -auto-approve

      - name: Output EC2 ip to file 
        run: |
           terraform output -raw vm_ip > instance_ip.txt

      - name: Upload instance IP file as artifact
        uses: actions/upload-artifact@v3
        with:
          name: instance-ip-file
          path: instance_ip.txt
  # Ansible Job
  ansible:
    runs-on: ubuntu-latest

    needs: terraform  # Ensures this job runs only after the terraform job completes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Install Ansible
        run: |
          sudo apt update
          sudo apt install -y software-properties-common
          sudo add-apt-repository --yes --update ppa:ansible/ansible
          sudo apt install -y ansible


      - name: Install Docker (for running the playbook)
        run: |
          sudo apt update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Download instance IP file
        uses: actions/download-artifact@v3
        with:
          name: instance-ip-file
         # path: instance_ip.txt

      - name: Read EC2 Instance IP
        run: |
          INSTANCE_IP=$(cat instance_ip.txt)
          echo "EC2 Instance IP: $INSTANCE_IP"  # Debugging output to check the IP

      - name: Set up Ansible inventory file
        run: |
          echo "[aws_servers]" > inventory.ini
          echo "$(cat instance_ip.txt) ansible_user=ec2-user ansible_ssh_private_key_file=my-key-pair.pem ansible_ssh_extra_args='-o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=publickey -o PasswordAuthentication=no'" >> inventory.ini

      - name: Debug Inventory File (optional)
        run: cat inventory.ini
        
      - name: Set up SSH private key
        run: |
          echo "${{ secrets.SSH_KEY }}" > my-key-pair.pem
          chmod 600 my-key-pair.pem  # Set permissions to read-only for the owner
          
      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i inventory.ini deploy-docker.yml

  # Docker Job
  docker:
    runs-on: ubuntu-latest

    needs: ansible  # Ensures this job runs only after the ansible job completes

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker
        run: |
          sudo apt update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: SSH into EC2 and run Docker commands
        run: |
          ssh -o StrictHostKeyChecking=no -i ${{ secrets.AWS_SSH_KEY }} ec2-user@${{ steps.terraform.outputs.instance_ip }} << 'EOF'
            # Pull the Docker image if needed (e.g., from Docker Hub or local registry)
            docker pull nginx:latest
            
            # Run the Docker container
            docker run -d -p 80:80 nginx:latest
          EOF

     # - name: Build Docker image
      #  run: |
     #     docker build -t nginx-image -f Dockerfile .

    #  - name: Run Docker container
     #   run: |
     #     docker run -d -p 80:80 nginx-image
